load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "buildfile",
    srcs = ["buildfile.go"],
    importpath = "github.com/Michaelhobo/nrfbazel/internal/buildfile",
    visibility = ["//nrfbazelify:__subpackages__"],
)
